wgd/wgd/urls.py
"""
Definition of urls for wgd.
"""

from datetime import datetime
from django.contrib.auth.decorators import login_required, permission_required
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
import django.contrib.auth.views
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy, path
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.base import RedirectView
from django.views.generic import TemplateView

# Enable the admin:
from wgd.settings import APP_PREFIX, STATIC_ROOT

# Imports for the app 'dictionary'
import wgd.dictionary.forms
from wgd.dictionary.views import *
from wgd.dictionary.adminviews import EntryListView, InfoListView


admin.autodiscover()

# set admin site names
admin.site.site_header = 'e-WGD Admin'
admin.site.site_title = 'e-WGD Site Admin'

pfx = APP_PREFIX

# ================ Custom error handling when debugging =============
def custom_page_not_found(request, exception=None):
    return wgd.dictionary.views.view_404(request)

handler404 = custom_page_not_found

urlpatterns = [
    # Examples:
    url(r'^$', wgd.dictionary.views.home, name='home'),
    path("404/", custom_page_not_found),
    url(r'^contact$', wgd.dictionary.views.contact, name='contact'),
    url(r'^about', wgd.dictionary.views.about, name='about'),
    url(r'^guide', wgd.dictionary.views.guide, name='guide'),
    url(r'^robots.txt', TemplateView.as_view(template_name='dictionary/robots.txt', content_type='text/plain')),
    url(r'^api/kloeke$', wgd.dictionary.views.kloeke_plaats, name='kloeke_plaats'),
    url(r'^delen', DeelListView.as_view(), name='delen'),
    url(r'^definitions$', RedirectView.as_view(url='/'+pfx+'admin/'), name='definitions'),
    url(r'^entries$', RedirectView.as_view(url='/'+pfx+'admin/dictionary/entry/'), name='entries'),
    url(r'^entries/import/$', permission_required('dictionary.search_gloss')(InfoListView.as_view()), name='admin_import_list'),
    url(r'^lemmas$', LemmaListView.as_view(), name='lemmas'),
    url(r'^lemma/search/$', LemmaListView.as_view(), name='lemmasearch'),
    url(r'^lemma/search/ajax/$', LemmaListView.as_view(), name='lemmasearch_ajax'),
    url(r'^lemma/map/(?P<pk>\d+)/$', csrf_exempt(LemmaMapView.as_view()), name='lemmamap'),
    url(r'^trefwoord/search/$', TrefwoordListView.as_view(), name='trefwoordsearch'),
    url(r'^dialects', DialectListView.as_view(), name='dialects'),
    url(r'^dialect/search/$', DialectListView.as_view(), name='dialectsearch'),
    url(r'^dialect/check/$', DialectCheckView.as_view(), name='dialectcheck'),
    url(r'^dialect/map/$', csrf_exempt(DialectMapView.as_view()), name='dialectmap'),
    url(r'^kloeke/search/$', KloekeListView.as_view(), name='kloekecodes'),
    url(r'^locations', LocationListView.as_view(), name='locations'),
    url(r'^location/search/$', LocationListView.as_view(), name='locationsearch'),
    url(r'^mines', MijnListView.as_view(), name='mines'),
    url(r'^mine/search/$', MijnListView.as_view(), name='minesearch'),
    url(r'^list/$', permission_required('dictionary.search_gloss')(EntryListView.as_view()), name='admin_entry_list'), 
    url(r'^dictionary/search/$', permission_required('dictionary.search_gloss')(EntryListView.as_view())),
    url(r'^entry/(?P<pk>\d+)', DictionaryDetailView.as_view(), name='output'),
    url(r'^import/start/$', wgd.dictionary.views.import_csv_start, name='import_start'),
    url(r'^import/progress/$', wgd.dictionary.views.import_csv_progress, name='import_progress'),

    url(r'^compare/$', permission_required('dictionary.search_gloss')(wgd.dictionary.views.do_compare), name='compare'),
    url(r'^repair/$', permission_required('dictionary.search_gloss')(wgd.dictionary.views.do_repair), name='repair'),
    url(r'^repair/start/$', wgd.dictionary.views.do_repair_start, name='repair_start'),
    url(r'^repair/progress/$', wgd.dictionary.views.do_repair_progress, name='repair_progress'),

    url(r'^static/(?P<path>.*)$',django.views.static.serve, {'document_root': STATIC_ROOT}),

    url(r'^login/$', LoginView.as_view
        (
            template_name= 'dictionary/login.html',
            authentication_form= wgd.dictionary.forms.BootstrapAuthenticationForm,
            extra_context= {'title': 'Log in','year': datetime.now().year,}
        ),
        name='login'),
    url(r'^logout$',  LogoutView.as_view(next_page=reverse_lazy('home')), name='logout'),

    # Uncomment the admin/doc line below to enable admin documentation:
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', admin.site.urls, name='admin_base'),
]

wgd/wgd/dictionary/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _
from wgd.dictionary.models import Entry, Lemma, Dialect, Mijn, Trefwoord, Kloeke

DIALECT_CHOICES = (
        ('code', 'Nieuwe Kloekecode'),
        ('stad', 'Plaats'),
        ('alles', 'Plaats en Kloekecode'),
    )

class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'User name'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Password'}))


class EntrySearchForm(forms.ModelForm):

    search = forms.CharField(label=_("Woord in het dialect"))
    sortOrder = forms.CharField(label=_("Sort Order"), initial="woord")
    lemma = forms.CharField(label=_("Begrip"))
    dialectCode = forms.CharField(label=_("Kloekecode"))
    dialectCity = forms.CharField(label=_("Stad"))
    aflevering = forms.CharField(label=_("Deel/sectie/aflevering"))

    class Meta:

        ATTRS_FOR_FORMS = {'class': 'form-control'};

        model = Entry
        fields = ('lemma', 'dialect', 'trefwoord', 'toelichting', 'kloeketoelichting', 'woord')


class CsvImportForm(forms.Form):
    success = forms.CharField(label=_("Status"), initial="")
    csvfile = forms.FileField(
        label="Selecteer een CSV bestand", 
        help_text="Het bestand moet de [tab] als scheidingsteken gebruiken")


#class LemmaSearchForm(forms.ModelForm):

#    search = forms.CharField(label=_("Begrip"))
#    sortOrder = forms.CharField(label=_("Sort Order"), initial="lemma")
#    woord = forms.CharField(label=_("Dialectopgave"))
#    dialectCode = forms.CharField(label=_("Kloeke code"))
#    dialectCity = forms.CharField(label=_("Plaats"))
#    bronnen = forms.CharField(label=_("Bronnen"))
#    optdialect = forms.CharField(label=_("Dialectweergave"))
#    aflevering = forms.CharField(label=_("Deel/sectie/aflevering"))
#    mijn = forms.CharField(label=_("Mijn"))
#    strict = forms.CharField(label=_("Strict filteren"))

#    class Meta:

#        ATTRS_FOR_FORMS = {'class': 'form-control'};

#        model = Lemma
#        fields = ('gloss', 'optdialect')


class LemmaSearchForm(forms.ModelForm):

    search = forms.CharField(label=_("Begrip"), required=False)
    sortOrder = forms.CharField(label=_("Sort Order"), initial="lemma", required=False)
    woord = forms.CharField(label=_("Dialectopgave"), required=False)
    dialectCode = forms.CharField(label=_("Kloeke code"), required=False)
    dialectCity = forms.CharField(label=_("Plaats"), required=False)
    bronnen = forms.CharField(label=_("Bronnen"), required=False)
    optdialect = forms.CharField(label=_("Dialectweergave"), required=False)
    aflevering = forms.CharField(label=_("Deel/sectie/aflevering"), required=False)
    mijn = forms.CharField(label=_("Mijn"), required=False)
    strict = forms.CharField(label=_("Strict filteren"), required=False)

    class Meta:

        ATTRS_FOR_FORMS = {'class': 'form-control'};

        model = Lemma
        fields = ('gloss', 'optdialect')

    def __init__(self, *args, **kwargs):
        # Perform standard initialization
        super(LemmaSearchForm, self).__init__(*args, **kwargs)
        # Make sure to disallow obligatoriness of fields
        self.fields['gloss'].required = False
        self.fields['optdialect'].required = False


class TrefwoordSearchForm(forms.ModelForm):

    search = forms.CharField(label=_("Trefwoord"))
    sortOrder = forms.CharField(label=_("Sort Order"), initial="woord")
    dialectwoord = forms.CharField(label=_("Dialectopgave"))
    lemma = forms.CharField(label=_("Begrip"))
    dialectCode = forms.CharField(label=_("Kloekecode"))
    dialectCity = forms.CharField(label=_("Plaats"))
    bronnen = forms.CharField(label=_("Bronnen"))
    optdialect = forms.CharField(label=_("Dialectweergave"))
    aflevering = forms.CharField(label=_("Deel/sectie/aflevering"))
    mijn = forms.CharField(label=_("Mijn"))
    strict = forms.CharField(label=_("Strict filteren"))

    class Meta:

        ATTRS_FOR_FORMS = {'class': 'form-control'};

        model = Trefwoord
        fields = ('woord', 'toelichting', 'optdialect')


class DialectSearchForm(forms.ModelForm):

    search = forms.CharField(label=_("Plaats"), required=False)
    nieuw = forms.CharField(label=_("Kloekecode"), required=False)
    sortOrder = forms.CharField(label=_("Sort Order"), initial="stad", required=False)
    aflevering = forms.CharField(label=_("Deel/sectie/aflevering"), required=False)
    mijn = forms.CharField(label=_("Mijn"), required=False)

    class Meta:

        ATTRS_FOR_FORMS = {'class': 'form-control'};

        model = Dialect
        fields = ('stad', 'code', 'nieuw')

    def __init__(self, *args, **kwargs):
        # Perform standard initialization
        super(DialectSearchForm, self).__init__(*args, **kwargs)
        # Make sure to disallow obligatoriness of fields
        self.fields['stad'].required = False
        self.fields['code'].required = False
        self.fields['nieuw'].required = False


class KloekeSearchForm(forms.ModelForm):

    sortOrder = forms.CharField(label=_("Sort Order"), initial="stad")

    class Meta:

        ATTRS_FOR_FORMS = {'class': 'form-control'};

        model = Kloeke
        fields = ('code', 'stad')


class MijnSearchForm(forms.ModelForm):

    search = forms.CharField(label=_("Mijn"))
    toelichting = forms.CharField(label=_("Toelichting"))
    locatie = forms.CharField(label=_("Locatie"))
    sortOrder = forms.CharField(label=_("Sort Order"), initial="naam")

    class Meta:

        ATTRS_FOR_FORMS = {'class': 'form-control'};

        model = Mijn
        fields = ('naam', 'locatie', 'toelichting')

wgd/wgd/dictionary/templates/dictionary/mijn_list.html
{% extends "dictionary/layout.html" %}

{% block content %}
      <div class="panel panel-default">
        <form name='dialectsearch' id='dialectsearch' action="" method='get' onsubmit="return do_search('#id_submit_button', 'mijn', 'simple');" >
            <!-- EK: A sort-order specification is in a hidden form field, which is filled by JS:do_sort_column() -->
            <div class="hidden">
                <input name='sortOrder' class='form-control' value='stad' >
                <input name='search_type' class='form-control' value='stad'>
                <input id="submit_type" name='submit_type' class='form-control' value='simple'>
            </div>

            <!-- The top layer of searching -->
            <div class="row"><table><tr><td>&nbsp;</td></tr></table></div>


            <div id="searchdefault" class="row">
              <div class="col-sm-3">
                <label>&nbsp;</label>
                <div class='input-group'>
                    <label class='input-group-addon' 
                           data-toggle="popover" data-trigger="hover"
                           data-placement="right" data-content="Willekeurige tekens: ? (één) * (0 of meer). Groep tekens: [m-n]"
                           for='id_entry'>{{searchform.search.label}}</label>
                    <input name='search' class='form-control' {% if searchform.search.value %}value='{{searchform.search.value}}'{% endif %}>
                </div>
              </div>
              <div class="col-sm-3">
                <label>&nbsp;</label>
                <div class='input-group'>
                    <label class='input-group-addon' 
                           data-toggle="popover" data-trigger="hover"
                           data-placement="right" data-content="Willekeurige tekens: ? (één) * (0 of meer). Groep tekens: [m-n]"
                           for='id_woord'>{{searchform.locatie.label}}</label>
                    <input name='locatie' class='form-control' {% if searchform.locatie.value %}value='{{searchform.locatie.value}}'{% endif %}>
                </div>
              </div>
              <div class="col-sm-3">
                <div><label>&nbsp;</label></div>
                <div class='btn-group'>
                    <!-- Make sure no button has the *name* 'submit', otherwise submit() cannot be used -->
                    <input class='btn btn-primary' type="submit" onclick="do_search(this, 'mijn', 'simple');" name="submit_type" value="Zoek">
                    <input class='btn btn-default' type="submit" onclick="do_search(this, 'mijn', 'Herstel');" name="submit_type" value="Herstel">
                </div>
              </div>
              <div class="col-sm-2">
                <div class='form-group' id='paginate_by'>
                  <label for='paginate_by'>Per pagina</label>
                  <select class='form-control' name="paginate_by">
                    {% for pag in paginateValues %}
                    <option {% if pag == paginateSize %} selected {% endif %}>{{pag}}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
            </div>

        </form>
      </div>

    {% if object_list %}
      <h3>Mijnen</h3>
      <div class="row">
          <div class="col-sm-4"><span>Gevonden: </span><span>{{entrycount}}</span></div>
          <div class="col-sm-8">
          <span class="step-links">

          {% include 'dictionary/pagination.html' %}

          </span>
          </div>
      </div>
      <table class="table table-hover">
        <thead><tr><th class="hidden">id</th><th>Mijn</th><th>Locatie</th><th>Toelichting</th></tr></thead>
        <tbody>
        {% for mine in object_list %}
          <tr class="dict-entry">
            <td class="hidden"> {{ mine.id }}</td>
            <td>
              <span class="mijn-naam"><a href="{% url 'minesearch' %}?search={{mine.naam}}">{{mine.naam}}</a></span>
            </td>
            <td>
              <span class="mijn-locatie">{{mine.locatie}}</span>
            </td>
            <td>
              <span class="toelichting">{{mine.toelichting}}</span>
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p>Er zijn geen mijnen om te tonen.</p>
    {% endif %}

      <div class="pagination">
          <span class="step-links">

          {% include 'dictionary/pagination.html' %}

          </span>
      </div>


{% endblock content %}

wgd/wgd/dictionary/templates/dictionary/trefwoord_list.html
{% extends "dictionary/layout.html" %}

{% block content %}
      <div class="panel panel-default">
        <form name='trefwoordsearch' id='trefwoordsearch' action="" method='get' 
              onsubmit="return do_search('#id_submit_button', 'trefwoord', 'simple');" >
            <!-- EK: A sort-order specification is in a hidden form field, which is filled by JS:do_sort_column() -->
            <div class="hidden">
                <input name='sortOrder' class='form-control' value='woord' >
                <input name='search_type' class='form-control' value='woord'>
                <input id="submit_type" name="submit_type" class='form-control' value="simple">
            </div>

            {% include 'dictionary/dialectviewing.html' %}

            <!-- The top layer of searching -->
            <div class="row"><table><tr><td>&nbsp;</td></tr></table></div>


            <div id="searchdefault" class="row">
              <div class="col-sm-4">
                <div><label>&nbsp;</label></div>
                <div class='input-group'>
                  <label class='input-group-addon' 
                         data-toggle="popover" data-trigger="hover"
                         data-placement="right" data-content="Willekeurige tekens: ? (één) * (0 of meer). Groep tekens: [m-n]"
                         for='id_entry'>{{searchform.search.label}}</label>
                  <input name='search' class='form-control' {% if searchform.search.value %}value='{{searchform.search.value}}'{% endif %}>
                </div>
              </div>
              <div class="col-sm-4 col-sm-offset-2">
                <div><label>&nbsp;</label></div>
                <div class='btn-group'>
                    <!-- Make sure no button has the *name* 'submit', otherwise submit() cannot be used -->
                    <input class='btn btn-primary' type="submit" onclick="do_search(this, 'trefwoord', 'simple');" value="Zoek">
                    <input class='btn btn-default' type="submit" onclick="do_search(this, 'trefwoord', 'Herstel');" value="Herstel">
                    <!-- <input class='btn btn-default' type="submit" onclick="do_search(this, 'trefwoord', 'Csv');" name="submit_type" value="Csv"> -->
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" 
                        aria-haspopup="true" aria-expanded="false">Download <span class="caret"></span></button>
                    <ul class="dropdown-menu">
                      <li><a href="#" onclick="do_search(this, 'trefwoord', 'Csv');" >Tab gescheiden lijst</a></li>
                      <li><a href="#" onclick="do_search(this, 'trefwoord', 'Excel');" >Excel</a></li>
                      <li><a href="#" onclick="do_search(this, 'trefwoord', 'Html');" >Html</a></li>
                    </ul>
                </div>
              </div>
              <div class="col-sm-2">
                <div class='form-group pull-right' id='paginate_by'>
                  <label for='paginate_by'>Per pagina</label>
                  <select class='form-control' name="paginate_by">
                    {% for pag in paginateValues %}
                    <option {% if pag == paginateSize %} selected {% endif %}>{{pag}}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
            </div>

            <!-- Collapsable area for fine-tuning -->
            <div class="row"><table><tr><td>&nbsp;</td></tr></table></div>
            <div class="panel panel-default">

              <div class="panel-heading" data-toggle="collapse" data-target="#query-area">
                <span>Filteren...</span>
                <span class="filter-summary">
                  <span class="filter-item">{% if searchform.lemma.value %}begrip={{searchform.lemma.value}}{% endif %}</span>
                  <span class="filter-item">{% if searchform.dialectwoord.value %}woord={{searchform.dialectwoord.value}}{% endif %}</span>
                  <span class="filter-item">{% if searchform.toelichting.value %}woord={{searchform.toelichting.value}}{% endif %}</span>
                  <span class="filter-item">{% if searchform.dialectCity.value %}plaats={{searchform.dialectCity.value}}{% endif %}</span>
                  <span class="filter-item">{% if searchform.dialectCode.value %}dialect={{searchform.dialectCode.value}}{% endif %}</span>
                  <span class="filter-item">{% if afl %}aflevering={{afl}}{% endif %}</span>
                  {% if mijnen|length > 0 %}
                    <span class="filter-item">{% if mijnnaam %}mijn={{mijnnaam}}{% endif %}</span>
                  {% endif %}
                </span>
              </div>

              <!-- class="collapse" -->
              <div id="query-area" class="collapse {% if not request.GET.search %} inert {% endif %}">

                <div id='searchformwell' class='well search-results-collapsable'>

                    <table class='table'>
                        <tr>
                          <td>
                            <div class='input-group'>
                              <label class='input-group-addon' 
                                      data-toggle="popover" data-trigger="hover"
                                      data-placement="right" data-content="Willekeurige tekens: ? (één) * (0 of meer). Groep tekens: [m-n]"
                                      for='id_lemma'>{{searchform.lemma.label}}</label>
                              <input name='lemma' class='form-control' {% if searchform.lemma.value %}value='{{searchform.lemma.value}}'{% endif %}>
                            </div>
                            <div><label>&nbsp;</label></div>
                            <div class='input-group'>
                              <label class='input-group-addon' 
                                      data-toggle="popover" data-trigger="hover"
                                      data-placement="right" data-content="Willekeurige tekens: ? (één) * (0 of meer). Groep tekens: [m-n]"
                                      for='id_dialectwoord'>{{searchform.dialectwoord.label}}</label>
                              <input name='dialectwoord' class='form-control' {% if searchform.dialectwoord.value %}value='{{searchform.dialectwoord.value}}'{% endif %}>
                            </div>
                            <div><label>&nbsp;</label></div>
                            <div class='input-group'>
                              <label class='input-group-addon' for='id_toelichting'>{{searchform.toelichting.label}}</label>
                              <input name='toelichting' class='form-control' {% if searchform.toelichting.value %}value='{{searchform.toelichting.value}}'{% endif %}>
                            </div>
                          </td>
                          <td>
                            <div class='input-group'>
                              <label class='input-group-addon' for='id_city'>{{searchform.dialectCity.label}}</label>
                              <input name='dialectCity' class='form-control' {% if searchform.dialectCity.value %}value='{{searchform.dialectCity.value}}'{% endif %}>
                            </div>
                            <div><label>&nbsp;</label></div>
                            <div class='input-group'>
                              <label class='input-group-addon' for='id_code'>{{searchform.dialectCode.label}}</label>
                              <input name='dialectCode' class='form-control' {% if searchform.dialectCode.value %}value='{{searchform.dialectCode.value}}'{% endif %}>
                            </div>
                            <div><label>&nbsp;</label></div>
                            <div class='input-group'>
                              <label class='input-group-addon' for='aflevering'>{{searchform.aflevering.label}}</label>
                              <select class='form-control' name="aflevering">
                                  <option value="0">-</option>
                                {% for opt in afleveringen %}
                                  <option  {% if opt.id == aflkeuze %} selected {% endif %} value="{{opt.id}}">{{opt.get_summary}}</option>
                                {% endfor %}
                              </select>
                            </div>

                            {% if mijnen|length > 0 %}
                              <div><label>&nbsp;</label></div>
                              <div class='input-group'>
                                <label class='input-group-addon' for='mijn'>{{searchform.mijn.label}}</label>
                                <select class='form-control' name="mijn">
                                    <option value="0">-</option>
                                  {% for opt in mijnen %}
                                    <option  {% if opt.id == mijnkeuze %} selected {% endif %} value="{{opt.id}}">{{opt.naam}}</option>
                                  {% endfor %}
                                </select>
                              </div>
                            {% endif %}

                          </td>
                        </tr>
                    </table>

              </div>
            </div>
            </div>
        </form>
      </div>

    {% if object_list %}
      <h3>Overzicht</h3>
      <div class="row">
          <div class="col-sm-3"><span>Gevonden: </span><span>{{entrycount}}</span></div>
          <div class="col-sm-9">
          <span class="step-links pull-right">

          {% include 'dictionary/pagination.html' %}

          </span>
          </div>
      </div>
      <table class="table table-hover">
        <thead><tr><th class="hidden">id</th><th>Trefwoord</th><th>Begrip: dialectopgave (plaats)</th><th>Toelichting</th></tr></thead>
        <tbody>
          {% for item in qlist %}
            {% if item.trefwoord_woord.first %}
              <tr class="dict-entry">
                <td class="hidden"> {{ item.entry.lemma.id }}</td>
                <td><span class="trefwoord-name">{{item.entry.trefwoord.woord}}</span></td>
                <td>
            {% endif %}
            {% if item.lemma_gloss.first  %}
              <!-- Start lemma -->
              <span class="lemma-name"><a href="{% url 'lemmasearch' %}?search={{item.entry.lemma.gloss|urlencode}}">{{item.entry.lemma.gloss}}</a>:</span>
            {% endif %}
            {% spaceless %}
              {% if item.toelichting.first and entry.toelichting != "" %}<span class="lemma-word-toelichting">{{item.entry.toelichting}}</span>&nbsp;{% endif %}
              {% if item.dialectopgave.first  %}
                <span class="lemma-word {% if item.entry.inwoordenboek == "false" %}lemma-word-electronic{% endif %}">{{item.entry.dialectopgave}}</span>
                <span> (</span>
              {% endif %}
              {% if item.entry.dialect.nieuw != "Q000" %}                
              <span class="lemma-word-dialect{% if not item.dialectopgave.first %}-additional hidden{% endif %}">
                <span class="lemma-word-dialect-code hidden">{{item.entry.dialect.nieuw}}</span>
                <span class="lemma-word-dialect-space hidden">&nbsp;</span>
                <span class="lemma-word-dialect-stad">{{item.entry.dialect.stad}}</span>
                {% if item.entry.kloeketoelichting != "" %}&nbsp;<span class="word-kloeketoelichting">[{{item.entry.kloeketoelichting}}]</span>&nbsp;{% endif %}
                {% if not item.dialectopgave.last %}<span>, </span>{% endif %}
                {% if item.dialectopgave.first and not item.dialectopgave.last %}
                  <span class="lemma-word-dialect-dots">...</span>
                {% endif %}
              </span>
              {% endif %}
              {% if item.entry.mijnlijst.count > 0 %}
                <span class="word-mijn">{% if  item.entry.dialect.nieuw != "Q000"  %}&nbsp;{% endif %}[</span>
                {% for mijn in item.entry.mijnlijst.all %}
                  <span class="word-mijn">{{mijn.naam}}</span>
                  <span class="word-mijn-letop">{% if not forloop.last %}, {% endif %}</span>
                {% endfor %}
                <span class="word-mijn">]</span>
              {% endif %}
              {% if item.dialectopgave.last %}
                <span>)</span>
              {% endif %}
              {% if item.dialectopgave.last and not item.trefwoord_woord.last %}<span>, </span>{% endif %}
            {% endspaceless %}
            {% if item.trefwoord_woord.last %}
                <!-- Treat the afleveringen for this trefwoord -->
                {% spaceless %}
                {% for item_afl in item.alist %}
                  {% if item_afl.afl.first %}
                    <span class="lemma-aflevering"><a href="/{{app_prefix}}static/dictionary/content/pdf/{{item_afl.entry.aflevering.get_pdf}}">{{item_afl.entry.aflevering.get_summary}}</a></span>
                  {% endif %}
                  {% if item_afl.afl.last and not forloop.last %}<span>, </span>{% endif %}
                {% endfor %}
                {% endspaceless %}
                </td>
                <td>
                  <span class="toelichting">{{item.trefwoord.toelichting}}</span>
                </td>
              </tr>
            {% endif %}
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p>No keywords are available.</p>
    {% endif %}

      <div class="pagination">
          <span class="step-links">

          {% include 'dictionary/pagination.html' %}
          </span>
      </div>


{% endblock content %}